# _config.yml
future: true
title: My Boekhoekie
baseurl: ""                        # no sub-path, Netlify lives at root
url: "https://boekresensies.netlify.app"

# ensure Jekyll copies admin/ verbatim
include:
  - admin

collections:
  posts:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
