# _config.yml
title: My Book Nook
# no baseurl
baseurl: ""
url: "https://boekresensies.netlify.app"

collections:
  posts:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
