# admin/config.yml

backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Book Reviews"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title",           name: "title",            widget: "string" }
      - { label: "Author",          name: "author",           widget: "string" }
      - { label: "Genre",           name: "genre",            widget: "select", options: ["Fiction","Non-Fiction","Sci-Fi","Romance","Biography"] }
      - { label: "Publication Date",name: "publication_date", widget: "datetime" }
      - { label: "Rating",          name: "rating",           widget: "number", value_type: "float", min: 0, max: 5, step: 0.5 }
      - { label: "Cover",           name: "cover",            widget: "image" }
      - { label: "Date",            name: "date",             widget: "datetime" }
      - { label: "Featured",        name: "featured",         widget: "boolean", default: false }
      - { label: "Author Bio",      name: "author_bio",       widget: "text",     required: false }
      - { label: "Tags",            name: "tags",             widget: "list",     default: [] }
      - { label: "Body",            name: "body",             widget: "markdown" }
