name: Build & Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Vendor Netlify CMS bundle
        run: |
          mkdir -p assets/vendor
          curl -sSL https://unpkg.com/netlify-cms@^2.17.0/dist/netlify-cms.js \
            -o assets/vendor/netlify-cms.js

      - name: Set up Ruby & install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.8"
          bundler-cache: true

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=_site --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:   ${{ secrets.NETLIFY_SITE_ID }}
